### ISSUE TITLE
Some changes are needed to run the Hooks sample

### ISSUE THREAD

**Issue by januswel** [auth0-samples/auth0-react-native-sample#119] opened 2023-06-29 09:55 UTC
### Checklist

- [X] I have looked into the Readme ([Base](https://github.com/auth0-samples/auth0-react-native-sample/tree/master/00-Login#readme)/[Hooks](https://github.com/auth0-samples/auth0-react-native-sample/tree/master/00-Login-Hooks#readme)/[Expo](https://github.com/auth0-samples/auth0-react-native-sample/tree/master/00-Login-Expo#readme)) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0-samples/auth0-react-native-sample/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I got errors and fix those
Upgrading React Native version may solve this issue fundamentally

### Reproduction

1. git clone
2. yarn
3. cd ios && pod install && cd -
4. yarn run ios
5. got errors

<img width="1512" alt="image" src="https://github.com/auth0-samples/auth0-react-native-sample/assets/43239/c132cd99-5e60-49bd-96a8-c94443f1dffa">

### Additional context

Editing the generated CocoaPods project with the following comment solved errors

https://github.com/facebook/react-native/issues/34106#issuecomment-1188225587

### Sample

Hooks

### Platform

iOS

### Platform version(s)

16.4

**Comment by poovamraj** [comment] 2023-09-11 13:56
Hi @januswel thanks for raising this. The sample is now running a more recent version of React Native and the issue is fixed now.

**Closed by poovamraj** 2023-09-11 13:56 UTC
